### ISSUE TITLE
Compile error?  Mac OS X High Sierra

### ISSUE THREAD

**Issue by grtessman** [horgh/videostreamer#3]
$ go get github.com/horgh/videostreamer
# github.com/horgh/videostreamer
videostreamer.c:87:18: error: no member named 'codecpar' in 'struct AVStream'
videostreamer.c:170:6: warning: implicit declaration of function 'avcodec_parameters_copy' is invalid in C99 [-Wimplicit-function-declaration]
videostreamer.c:170:42: error: no member named 'codecpar' in 'struct AVStream'
videostreamer.c:171:16: error: no member named 'codecpar' in 'struct AVStream'

**Comment by horgh** [comment]
I suspect the version of ffmpeg you have is incompatible somehow. What version do you have?

**Comment by grtessman** [comment]
$ ffmpeg -version
ffmpeg version 3.0.2 Copyright (c) 2000-2016 the FFmpeg developers
built with Apple LLVM version 8.1.0 (clang-802.0.42)
configuration: --prefix=/usr/local/Cellar/ffmpeg/3.0.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libxvid --enable-ffplay --enable-libfdk-aac --enable-libx265 --enable-nonfree --enable-vda
libavutil      55. 17.103 / 55. 17.103
libavcodec     57. 24.102 / 57. 24.102
libavformat    57. 25.100 / 57. 25.100
libavdevice    57.  0.101 / 57.  0.101
libavfilter     6. 31.100 /  6. 31.100
libavresample   3.  0.  0 /  3.  0.  0
libswscale      4.  0.100 /  4.  0.100
libswresample   2.  0.101 /  2.  0.101
libpostproc    54.  0.100 / 54.  0.100

**Comment by horgh** [comment]
I see, thanks for the information. Yeah, I've only known this to work with 3.2+. Some of the APIs there were deprecated and because of that videostreamer uses the new ones. This is probably one of them.

Is updating ffmpeg an option for you?

I can look into making it compatible with the older version, but it will probably not be something I can fix quickly.

**Comment by grtessman** [comment]
That sounds like the right move for me to try upgrading to 3.2.   I should be able to do that on Mac OS X.  Thank you for the info.  I don't think it'd be worth your time to make it work with older versions of ffmpeg.  Code to the future, not the past :-)  I'll close this issue.  Thank you again.
